version: 1
formatters:
  verbose:
    format: "[%(asctime)s] %(levelname)s %(name)s: %(message)s | endpoint=%(endpoint)s tenant_id=%(tenant_id)s status=%(status)s duration_ms=%(duration_ms)s error=%(error)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: verbose
    stream: ext://sys.stdout
loggers:
  rag_sdk:
    handlers: [console]
    level: INFO
    propagate: false
root:
  handlers: [console]
  level: INFO
